//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dads_Last_Week.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public decimal Id { get; set; }
        public decimal Jugador { get; set; }
        public string Nom_Personaje { get; set; }
        public short Porcentaje_Salud { get; set; }
        public string Estado { get; set; }
        public string Decision_Final { get; set; }
    
        public virtual Decision Decision { get; set; }
        public virtual Jugador Jugador1 { get; set; }
    }
}
